// <auto-generated />
namespace Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class slots : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(slots));
        
        string IMigrationMetadata.Id
        {
            get { return "202302031304328_slots"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
